services:
  payload:
    image: node:18-alpine
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: >
      sh -c "
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        pnpm install --frozen-lockfile &&
        pnpm build &&
        pnpm serve
      "

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  node_modules: